### ISSUE TITLE
Author profile page is empty

### ISSUE THREAD

**Issue by GanimanSwift** [professionalaf/hugo-news#2]
This theme is nice and clean, however the author pages seem to be empty when you go to the full profile. Only the name appears as a head, but no content between that and the footer.

**Comment by maafk** [comment]
@GanimanSwift Thanks for opening this issue!

Working it now

**Comment by maafk** [comment]
@GanimanSwift Check your `config.toml` on your site.

Try adding

```toml
[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags" 
```

Do you still experience this behavior?
